### ISSUE TITLE
🐅 Epic: Test new generative models

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/3d-analogues#3]
**Summary**
We used ChemSampler for a first round of generation of dCA analogues, which were evaluated by docking scores only. We still want to get more diversity of compounds so we have been working on incorporating more generative models.
We have also identified other ways of evaluating the results, mainly via 3D Shape analysis (see this [repository](github.com/ersilia-os/vsflow-ligand-based-3d-screening/). We have discarded the option of training a bioactivity predictor due to the lack of data on HIV-TAT inhibition.  Now we want to evaluate how these new generative models perform and increase the similarity searches to 3D space.
By model testing it means:
- Checking that the models do work as expected 
- Checking which results and how many they give for our example compound, dCA
- Evaluating these results using the docking and 3D Shape analysis

**Objectives**

- [x] Test Reinvent models added to the Hub: eos57bx, eos6ost
- [ ] Test SAFE models: eos2401, eos8bhe
- [ ] Test SQUID (eos8vud)
- [x] Test PGMG (eos69e6)
- [x] test smplers with Whales descriptors: eos6ru3
- [ ] Implement similarity search using whales of Chembl - like eos1noy

**Documentation**
Previous iterations of chemsampler:
https://ersilia.gitbook.io/ersilia-book

**Comment by GemmaTuron** [comment]
@miquelduranfrigola and @DhanshreeA 
Can you confirm the status of the following models:
- eos2401
- eos8vud
- eos69e6
I am meanwhile testing the others as described

**Comment by miquelduranfrigola** [comment]
eos8vud and eos69e6 are WIP

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 

This week you confirmed eos69e6 was done. Can you please clarify?

**Comment by miquelduranfrigola** [comment]
The model is done - I just said "WIP" since I assumed it did not work for you, so I wanted to check what might be going on. But as far as I am concerned, it works.

**Comment by GemmaTuron** [comment]
Ok, I have tested the following models using dCA as a seed molecule: eos6ost, eos57bx, eos69e6, eos6ru3 and eos8bhe (this last one did not produce results).
They generate between 100 - 1000 molecules each, so I am now working on the best way to evaluate those molecules, as docking is very slow for that purpose. See #4 for more.

**Comment by miquelduranfrigola** [comment]
Closing as backlog housekeeping — this issue is over a year old and the repository is currently Idle (not under active development). Closed as not planned, not resolved; please reopen if work on this resumes.
